title: MEI Music Archive
description: Interactive catalog of encoded musical works

collections:
  works:
    output: true
    permalink: /works/:path/


baseurl: "/Edition-Platform"


defaults:
  - scope:
      path: ""
      type: works
    values:
      layout: work

markdown: kramdown
